services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: internal-portal-db
    environment:
      SA_PASSWORD: "YourStrong@Passw0rd"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sqlserver-data:/var/opt/mssql
    healthcheck:
      test: /opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P "YourStrong@Passw0rd" -C -Q "SELECT 1" || exit 1
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s

  mailpit:
    image: axllent/mailpit
    container_name: internal-portal-mailpit
    ports:
      - "8025:8025"
      - "1025:1025"

  api:
    build:
      context: .
      dockerfile: src/Presentation/InternalPortal.API/Dockerfile
    container_name: internal-portal-api
    ports:
      - "5001:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=InternalPortalDb;User Id=sa;Password=YourStrong@Passw0rd;TrustServerCertificate=True
      - Smtp__Host=mailpit
      - Smtp__Port=1025
    depends_on:
      sqlserver:
        condition: service_healthy
    volumes:
      - api-uploads:/app/uploads

  web:
    build:
      context: src/Frontend/internal-portal-web
      args:
        NEXT_PUBLIC_API_URL: http://localhost:5001
    container_name: internal-portal-web
    ports:
      - "3000:3000"
    depends_on:
      - api

volumes:
  sqlserver-data:
  api-uploads:
